### ISSUE TITLE
tweaks - objects and usability

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#186]
- [x] tag lists as frozensets #126 
- [x] some use of VTime and TagID per #183
- [x] XX in audit lists for retired tags #176 
- [x] #187 
- [x] #171 
- [x] "projected to end of day" rather than "as at 24:00" on reports
- [x] use case controls in TagID() rathr than folding case on main data structures
Also
- [x] chase down \bTag\b and \bTime\b references
- [ ] #192
- [x] check all min() and max() calls to see list will never be empty (e.g. `max([list comprehension] + [0])`
- [x] #190

**Comment by tevpg** [comment]
This is in PR #189
