### ISSUE TITLE
server-side updating and use of database

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#217]
find a database home on a server
- [ ] #216 update it from google-drive 'latest.dat'
- [ ] #194  CGI reporting, continued
- [ ] #195 mailer to city hall
